### PR TITLE
This commit:

### PR DESCRIPTION
**Pull request by objectkuan**
- adds FromUserRecordLDAPGroupMembershipStrategy (refer to:
  https://github.com/jenkinsci/ldap-plugin/tree/master/src/main/java/jenkins/security/plugins/ldap);
- fixes cases when rootDN is empty and needs to be inferred;
- fixes trivial code style nits.

### CODE REVIEW

**Comment by objectkuan** [comment]
Hi, this seems to be a non-trivial change, please review and advise.
Thanks.

**Comment by mengzhaopeng** [comment]
Hi, thank for your PR.
I merged your code into my test environment and builded image.
Added startup parameter to the file (docker-compose.yml).
    ....
    LDAP_GROUP_MEMBERSHIP_STRATEGY: FromGroupSearchLDAPGroupMembershipStrategy
    LDAP_GROUP_MEMBERSHIP_SEARCH_FILTER: (& (cn=users) (objectclass=posixGroup))
    ....
When jenkins started, the following error occurred.
    ....
    SEVERE: A thread (Thread-7/54) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
groovy.lang.MissingPropertyException: No such property: ldap_groupSearchFilter for class: ldap
    ....
When I modified the startup parameters to another setting, the error log is the same.
    ....
    LDAP_GROUP_MEMBERSHIP_STRATEGY: FromUserRecordLDAPGroupMembershipStrategy
    LDAP_USER_RECORD_ATTRIBUTE_NAME: memberOf
    ....
    ....
    SEVERE: A thread (Thread-7/54) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
groovy.lang.MissingPropertyException: No such property: ldap_groupSearchFilter for class: ldap
    ....
Is there a problem with my startup parameters?
Thanks.

**Comment by objectkuan** [comment]
Hmm.. Everything looks normal and I've not any idea in my mind so far.
Intuitively the problem comes from the ldap groovy file. Is there any chance to check that file?

**Comment by mengzhaopeng** [comment]
hi, I found the cause of the problem.
The startup parameters are modified as follows:
....
LDAP_GROUP_MEMBERSHIP_STRATEGY: FromGroupSearchLDAPGroupMembershipStrategy
LDAP_GROUP_MEMBERSHIP_SEARCH_FILTER: (& (cn={0}) (objectclass=posixGroup) )
....
Thanks again for your PR.

**Comment by thinkernel** [comment]
Hi @objectkuan 
Thanks a lot for the contribution.

**Pull request merged**
